[WIP][DNM]Add periodicStart() to support cron builds
screwdriver-cd/executor-queue pull request #12
Opened 2018-04-25 18:40 UTC by pranavrc

--To be filled--

Do not merge.

2018-04-26 00:25 UTC, minzcmu requested changes

2018-04-26 00:25 UTC, minz1027 commented on index.js
> +        await this.scheduler.connect();
Do not create new connection everytime, it creates some weird effect. Try to do something like `this.connect()` function: https://github.com/screwdriver-cd/executor-queue/blob/608e644846536afb012f1eaba0acf8f71725c393/index.js#L171

2018-04-26 17:57 UTC, d2lam commented on index.js
> +     * @param {Boolean}config.update        Boolean to determine if updating existing periodic build
should name this `isUpdate` to make it clearer

2018-04-26 17:58 UTC, d2lam commented on index.js
> +     * @param {Object} config.tokenGen      Function to generate JWT from username, scope and scmContext
This is a Function

2018-04-26 17:59 UTC, d2lam commented on index.js
> +    async _startPeriodic(config) {
`async _startPeriodic({pipeline, job, tokenGen, update = false})`
and you can remove the next 4 lines for initialization.

2018-04-26 18:00 UTC, d2lam requested changes

2018-04-26 18:00 UTC, d2lam commented on index.js
> +        const buildCron = job.annotations.buildPeriodically;
this is all under `permutations`

2018-04-30 22:56 UTC, pranavrc commented
Opened a new PR here: https://github.com/screwdriver-cd/executor-queue/pull/14

Closing this one.

2018-04-30 22:56 UTC, closed without merging